#
# Copyright 2016 Freescale Semiconductor
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += imx8mq_phanbell.o

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
obj-y += board_id.o
obj-y += ddr/lpddr4_timing_v22.o
endif
